### ISSUE TITLE
Fetching data with empty id query parameter

### ISSUE THREAD

**Issue by jonny-no1** [fourlabsldn/fl-multi-calendar-2#1]
When viewing the demo, the calendar sends two requests to fetch the events data. The first one seems to be redundant and irrelevant, as it has an empty `id` query parameter.

**Comment by lazamar** [comment]
Solved by https://github.com/fourlabsldn/fl-multi-calendar-2/commit/74e312568a98d769af8d67584422cbc036ba0b7c
