### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by jonny-no1** [fourlabsldn/fl-multi-calendar-2#6]
I added the missing dev dependency but the build is still failing. Could migrate travis to yarn?

https://travis-ci.org/fourlabsldn/fl-multi-calendar-2/builds/203745486

**Comment by lazamar** [comment]
Fixed by ff65e9aaaf0b5f75b48e6f2b54c451e8c6ba917e

**Comment by jonny-no1** [comment]
thanks @lazamar!

**Comment by lazamar** [comment]
You are very welcome @foaly-nr1
